# ============================================================
# src/export.py
# PDF Report Export for Research Workflow Results
#
# Uses fpdf2 to generate formatted PDF reports from the
# agentic workflow results.
# ============================================================

import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

try:
    from fpdf import FPDF
except ImportError:
    FPDF = None
    logger.warning("fpdf2 not installed. PDF export disabled. Run: pip install fpdf2")


class ResearchReportPDF:
    """
    Generates a formatted PDF report from agentic workflow results.

    Usage:
        exporter = ResearchReportPDF()
        pdf_bytes = exporter.generate(topic, final_state)
    """

    def __init__(self):
        if FPDF is None:
            raise ImportError("fpdf2 is required for PDF export. Install with: pip install fpdf2")

    def generate(self, topic: str, state: dict) -> bytes:
        """
        Generate a complete PDF report from the workflow state.

        Args:
            topic: The research topic.
            state: The final state dict from the agentic workflow.

        Returns:
            PDF content as bytes.
        """
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)

        # ── Cover Page ──
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 28)
        pdf.ln(40)
        pdf.cell(0, 15, "Research Report", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_font("Helvetica", "", 14)
        pdf.ln(5)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, "Generated by Research Paper Intelligence Engine", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(20)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "B", 16)
        pdf.multi_cell(0, 10, f"Topic: {topic}", align="C")
        pdf.ln(10)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%B %d, %Y at %H:%M')}", new_x="LMARGIN", new_y="NEXT", align="C")
        num_papers = len(state.get("selected_papers", []))
        pdf.cell(0, 8, f"Papers Analyzed: {num_papers}", new_x="LMARGIN", new_y="NEXT", align="C")

        # ── Top Ranked Papers ──
        pdf.add_page()
        self._section_header(pdf, "Top Ranked Papers")

        for i, paper in enumerate(state.get("selected_papers", []), start=1):
            title = paper.get("title", "Unknown")
            year = paper.get("year", "N/A")
            score = paper.get("relevance_score", 0)
            authors = ", ".join(paper.get("authors", [])[:3])
            if len(paper.get("authors", [])) > 3:
                authors += " et al."

            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(0, 100, 200)
            pdf.cell(0, 7, f"{i}. {self._safe(title)}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 5, f"   Year: {year}  |  Relevance Score: {score:.3f}", new_x="LMARGIN", new_y="NEXT")
            if authors:
                pdf.cell(0, 5, f"   Authors: {self._safe(authors)}", new_x="LMARGIN", new_y="NEXT")

            abstract = paper.get("abstract", "")
            if abstract:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 4, f"   {self._safe(abstract[:300])}...")
                pdf.set_text_color(0, 0, 0)
            pdf.ln(4)

        # ── Structured Analysis ──
        analyses = state.get("analyses", [])
        if analyses:
            pdf.add_page()
            self._section_header(pdf, "Structured Analysis")

            for p in analyses:
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(0, 100, 200)
                pdf.cell(0, 8, self._safe(p.get("title", "Unknown")), new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(0, 0, 0)

                fields = [
                    ("Research Problem", p.get("research_problem", "")),
                    ("Objective", p.get("objective", "")),
                    ("Proposed Method", p.get("proposed_method", "")),
                    ("Dataset", p.get("dataset", "")),
                    ("Evaluation Metrics", p.get("evaluation_metrics", "")),
                    ("Results", p.get("experimental_results", "")),
                ]

                for label, value in fields:
                    if value and value != "Not explicitly stated.":
                        pdf.set_font("Helvetica", "B", 9)
                        pdf.cell(40, 5, f"  {label}:", new_x="END")
                        pdf.set_font("Helvetica", "", 9)
                        pdf.multi_cell(0, 5, f" {self._safe(str(value)[:200])}")

                # Key Findings
                findings = p.get("key_findings", [])
                if findings:
                    pdf.set_font("Helvetica", "B", 9)
                    pdf.cell(0, 6, "  Key Findings:", new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font("Helvetica", "", 8)
                    if isinstance(findings, list):
                        for f in findings[:3]:
                            pdf.multi_cell(0, 4, f"    - {self._safe(str(f)[:150])}")
                    else:
                        pdf.multi_cell(0, 4, f"    {self._safe(str(findings)[:300])}")

                pdf.ln(6)
                pdf.set_draw_color(200, 200, 200)
                pdf.line(pdf.get_x() + 10, pdf.get_y(), pdf.get_x() + 180, pdf.get_y())
                pdf.ln(4)

        # ── Multi-Paper Comparison Table ──
        if analyses:
            pdf.add_page("L")  # Landscape for table
            self._section_header(pdf, "Multi-Paper Comparison")

            # Table header
            col_widths = [60, 55, 50, 55, 55]
            headers = ["Paper", "Method", "Dataset", "Key Findings", "Limitations"]

            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(230, 240, 250)
            for i, header in enumerate(headers):
                pdf.cell(col_widths[i], 7, header, border=1, fill=True, align="C")
            pdf.ln()

            # Table rows
            pdf.set_font("Helvetica", "", 7)
            for p in analyses:
                title = self._safe(p.get("title", "")[:40])
                method = self._safe(str(p.get("proposed_method", ""))[:40])
                dataset = self._safe(str(p.get("dataset", ""))[:35])

                findings = p.get("key_findings", "")
                if isinstance(findings, list):
                    findings = findings[0] if findings else ""
                findings = self._safe(str(findings)[:40])

                limitations = p.get("limitations", "")
                if isinstance(limitations, list):
                    limitations = limitations[0] if limitations else ""
                limitations = self._safe(str(limitations)[:40])

                row_data = [title, method, dataset, findings, limitations]
                for i, cell_text in enumerate(row_data):
                    pdf.cell(col_widths[i], 6, cell_text, border=1)
                pdf.ln()

        # ── Literature Review ──
        lit_review = state.get("literature_review", "")
        if lit_review:
            pdf.add_page("P")  # Back to portrait
            self._section_header(pdf, "Literature Review")
            pdf.set_font("Helvetica", "", 10)
            # Parse markdown-style sections
            for line in lit_review.split("\n"):
                line = line.strip()
                if not line:
                    pdf.ln(3)
                    continue
                if line.startswith("## "):
                    pdf.set_font("Helvetica", "B", 13)
                    pdf.set_text_color(0, 80, 160)
                    pdf.cell(0, 8, self._safe(line[3:]), new_x="LMARGIN", new_y="NEXT")
                    pdf.set_text_color(0, 0, 0)
                elif line.startswith("### "):
                    pdf.set_font("Helvetica", "B", 11)
                    pdf.set_text_color(80, 40, 120)
                    pdf.cell(0, 7, self._safe(line[4:]), new_x="LMARGIN", new_y="NEXT")
                    pdf.set_text_color(0, 0, 0)
                elif line.startswith("- "):
                    pdf.set_font("Helvetica", "", 9)
                    pdf.multi_cell(0, 5, f"  \u2022 {self._safe(line[2:])}")
                elif line.startswith("---"):
                    pdf.ln(3)
                    pdf.set_draw_color(180, 180, 180)
                    pdf.line(pdf.get_x() + 10, pdf.get_y(), pdf.get_x() + 180, pdf.get_y())
                    pdf.ln(3)
                else:
                    pdf.set_font("Helvetica", "", 9)
                    pdf.multi_cell(0, 5, self._safe(line))

        # ── Footer on all pages ──
        # fpdf2 doesn't have a built-in footer callback like reportlab,
        # so we just add a note at the end
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 5, "Generated by Research Paper Intelligence Engine | Agentic AI Research Assistant", align="C")

        return pdf.output()

    def _section_header(self, pdf, title: str):
        """Add a styled section header."""
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(0, 80, 160)
        pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(0, 150, 220)
        pdf.set_line_width(0.5)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
        pdf.ln(6)
        pdf.set_text_color(0, 0, 0)
        pdf.set_line_width(0.2)

    def _safe(self, text: str) -> str:
        """Make text safe for fpdf2 (handle encoding issues)."""
        if not text:
            return ""
        # Replace characters that fpdf2 can't encode in latin-1
        return text.encode("latin-1", errors="replace").decode("latin-1")
